version: '3'

services:
  database:
    build: .docker/postgres
    container_name: estacio-postgres
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=senha
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - database
